Omit Custom Request Guards
Kindness-Works/rocket-ts pull request #5
Opened 2024-03-18 21:53 UTC by AvaterClasher

Nothing fancy just storing the req guards in a vector and comparing the types against it. If we don't get a exclude type we return a empty vec so that the compiler doesnt panic.

In the base folder -> create `exclusion.txt || exclusion.toml` anything really.

`cargo run generate -i example-handlers -o k7.ts -e exclusion.toml `

2024-03-19 14:02 UTC, dteare commented
I don't see how the exclusion list could be a `toml` file. Afaict from the parsing code you're expecting a file of new-line separated strings.

2024-03-19 14:18 UTC, dteare requested changes
I left some comments.

2024-03-19 14:18 UTC, dteare commented on src/main.rs
> +            help = "Exclusion file",
This help text could be so much more helpful to the user. As far as I know this is _only_ used for excluding parameters from the generated interface, and it's (likely?) only useful for Request Guards. It'd be helpful to touch on these concepts here so the reader can quickly piece together why they would want this.

2024-03-19 14:18 UTC, dteare commented on src/main.rs
> +                // If no exclusion file is provided, initializing an empty exclusion list so the compiler doesnt panic
This comment isn't needed. It just seems to get in the way.

2024-03-19 14:18 UTC, dteare commented on src/parser/params_as_comma_seperated.rs
> +/// * `args` - A vector of `FnArg` items representing the arguments of a function.
I struggle with `Arguments` comments as they need to be maintained and personally I find just reading the code `args: Vec<FnArg>` directly is faster and easier to understand. To me this practice is really just an artifact from earlier languages that lacked strict typing and lack value in Rust. Especially for internal modules.

2024-03-19 14:18 UTC, dteare commented on src/parser/exclusion_parser.rs
> +pub fn parse_exclusion_file(exclusion_file_path: &String) -> Vec<String> {
As a user of `rocket-ts` I would expect an error if I provided a file that didn't exist and the program should halt. The parser can't be responsible for that so a `Result` type is really needed here.

2024-03-19 14:18 UTC, dteare commented on src/parser/exclusion_parser.rs
> +        contents.lines().map(|line| line.trim().to_string()).collect()
It really feels like there should be some sort of validation of the contents of the file. Maybe I'm over thinking it though.

2024-03-19 14:18 UTC, dteare commented on src/parser/exclusion_parser.rs
> +        Vec::new()
With a `Result` type this wouldn't be needed.

2024-03-20 17:47 UTC, AvaterClasher commented on src/main.rs
> +            help = "Exclusion file",
Left helpful message for the user.

2024-03-20 17:47 UTC, AvaterClasher commented on src/main.rs
> +                // If no exclusion file is provided, initializing an empty exclusion list so the compiler doesnt panic
Removed

2024-03-20 18:14 UTC, AvaterClasher commented on src/parser/exclusion_parser.rs
> +pub fn parse_exclusion_file(exclusion_file_path: &String) -> Vec<String> {
Added a result type to handle if the file didnt exist. the programs stop execution if that happens.

2024-03-20 18:16 UTC, AvaterClasher commented on src/parser/exclusion_parser.rs
> +        contents.lines().map(|line| line.trim().to_string()).collect()
Even if the user adds something weird I don't think that matters much as we are just matching the parsed result types against the excluded one's. So if they don't match they are naturally just ignored.

2024-03-20 18:16 UTC, AvaterClasher commented on src/parser/exclusion_parser.rs
> +        Vec::new()
Done in the previous commit

2024-03-21 14:30 UTC, dteare commented on src/parser/params_as_comma_seperated.rs
> +/// * `args` - A vector of `FnArg` items representing the arguments of a function.
Yes. I think it reads much better w/o them.

2024-03-26 11:51 UTC, AvaterClasher commented
Hey @dteare,

I've addressed all of the Clippy warnings now. Regarding the error messages, I've included the filename along with the error. I plan to remove the `eprintln!` macro once I integrate the logging framework later on.

Could you please provide your suggestions for the README.md? Specifically, I'm thinking about the example section. Should I remove the upper part of it, or would you recommend it staying?

Thank you.

2024-04-02 17:57 UTC, dteare commented
Some nice updates here. Thanks for continuing your work here @AvaterClasher. Closing in favour of PR #6, which includes all your commits with my edits applied on top.

2024-04-02 17:57 UTC, closed without merging